# General settings

debug: false

logDirectory: logs

ticketUrlsCauseEmbed: false

forbiddenTicketPrefix: '!'

requiredTicketPrefix: ''

filterRemovalTimeout: 300000

embedDeletionEmoji: 'ğŸ—‘ï¸'

projects:
  - BDS
  - MC
  - MCCE
  - MCD
  - MCL
  - MCPE
  - REALMS
  - WEB

request:
  invalidTicketEmoji: â¸
  noLinkEmoji: â›”
  warningLifetime: 5000
  waitingEmoji: âŒ›

  invalidRequestJql: created > -24h

  suggestedEmoji:
    - âœ…
    - â˜‘ï¸
    - âŒ
    - ğŸ’¬
    - ğŸ“

  ignorePrependResponseMessageEmoji: âœ…
  ignoreResolutionEmoji: ğŸ’¬
  bulkEmoji: ğŸ“

  resolveDelay: 10000
  prependResponseMessage: whenResolved
  prependResponseMessageInLog: false

  responseMessage: |-
    ```
    {{author}} {{url}}
    {{message}}

    ```
