# General settings

debug: false

logDirectory: logs

ticketUrlsCauseEmbed: false

forbiddenTicketPrefix: '!'

requiredTicketPrefix: ''

projects:
  - BDS
  - MC
  - MCAPI
  - MCCE
  - MCD
  - MCE
  - MCL
  - MCPE
  - REALMS
  - WEB

request:
  noLinkEmoji: â›”
  noLinkWarningLifetime: 5000
  waitingEmoji: âŒ›

  suggestedEmoji:
    - âœ…
    - â˜‘ï¸
    - âŒ
    - ğŸ’¬
    - ğŸ“
  
  ignorePrependResponseMessageEmoji: âœ…
  ignoreResolutionEmoji: ğŸ’¬
  bulkEmoji: ğŸ“

  resolveDelay: 10000
  prependResponseMessage: whenResolved
  prependResponseMessageInLog: false

  responseMessage: |-
    ```
    {{author}} {{url}}
    {{message}}
    
    ```
