# General settings

debug: false

logDirectory: logs

ticketUrlsCauseEmbed: false

forbiddenTicketPrefix: '!'

requiredTicketPrefix: ''

projects:
  - BDS
  - MC
  - MCAPI
  - MCCE
  - MCD
  - MCE
  - MCL
  - MCPE
  - REALMS
  - WEB

request:
  invalidTicketEmoji: ‚è∏
  noLinkEmoji: ‚õî
  warningLifetime: 5000
  waitingEmoji: ‚åõ

  invalidRequestJql: created < 24h

  suggestedEmoji:
    - ‚úÖ
    - ‚òëÔ∏è
    - ‚ùå
    - üí¨
  
  ignorePrependResponseMessageEmoji: ‚úÖ
  ignoreResolutionEmoji: üí¨

  resolveDelay: 10000
  prependResponseMessage: whenResolved
  prependResponseMessageInLog: false

  responseMessage: |-
    ```
    {{author}} {{url}}
    {{message}}
    
    ```
