# General settings

debug: false

logDirectory: logs

ticketUrlsCauseEmbed: false

forbiddenTicketPrefix: '!'

requiredTicketPrefix: ''

embedDeletionEmoji: 'ğŸ—‘ï¸'

projects:
  - BDS
  - MC
  - MCAPI
  - MCCE
  - MCD
  - MCE
  - MCL
  - MCPE
  - REALMS
  - WEB

request:
  noLinkEmoji: â›”
  noLinkWarningLifetime: 5000
  waitingEmoji: âŒ›

  suggestedEmoji:
    - âœ…
    - â˜‘ï¸
    - âŒ
    - ğŸ’¬
  
  ignorePrependResponseMessageEmoji: âœ…
  ignoreResolutionEmoji: ğŸ’¬

  resolveDelay: 10000
  prependResponseMessage: whenResolved
  prependResponseMessageInLog: false

  responseMessage: |-
    ```
    {{author}} {{url}}
    {{message}}
    
    ```
