# General settings

debug: false

logDirectory: logs

ticketUrlsCauseEmbed: false

forbiddenTicketPrefix: '!'

requiredTicketPrefix: ''

projects:
  - BDS
  - MC
  - MCAPI
  - MCCE
  - MCE
  - MCL
  - MCPE
  - WEB

request:
  noLinkEmoji: â›”
  noLinkWarningLifetime: 5000
  waitingEmoji: âŒ›

  suggestedEmoji:
    - âœ…
    - â˜‘ï¸
    - âŒ
  
  ignorePrependResponseMessageEmoji: âœ…

  resolveDelay: 10000
  prependResponseMessage: whenResolved
  prependResponseMessageInLog: false

  responseMessage: |-
    ```
    {{author}} {{url}}
    > {{message}}
    
    ```
feed:
  feedEmoji: ðŸŽ‰

filterFeedInterval: 30000
versionFeedInterval: 30000
