# General settings

debug: false

logDirectory: logs

ticketUrlsCauseEmbed: false

forbiddenTicketPrefix: '!'

requiredTicketPrefix: ''

projects:
  - BDS
  - MC
  - MCAPI
  - MCCE
  - MCD
  - MCE
  - MCL
  - MCPE
  - REALMS
  - WEB

request:
  noLinkEmoji: ‚õî
  noLinkWarningLifetime: 5000
  waitingEmoji: ‚åõ

  suggestedEmoji:
    - ‚úÖ
    - ‚òëÔ∏è
    - ‚ùå
    - üí¨
  
  ignorePrependResponseMessageEmoji: ‚úÖ
  ignoreResolutionEmoji: üí¨

  fullNotificationsRole: 'All Request Notifications'
  someNotificationsRole: 'Fewer Request Notifications'
  oldNotificationsRole: 'Old Request Notifications'
  oldNotificationsTimeDifference: 259200000 # 3 days

  resolveDelay: 10000
  prependResponseMessage: whenResolved
  prependResponseMessageInLog: false

  responseMessage: |-
    ```
    {{author}} {{url}}
    {{message}}
    
    ```
