# General settings

debug: false

logDirectory: logs

ticketUrlsCauseEmbed: false

quotedTicketsCauseEmbed: false

forbiddenTicketPrefix: '!'

requiredTicketPrefix: ''

embedDeletionEmoji: 'ğŸ—‘ï¸'

maxSearchResults: 5

projects:
  - BDS
  - MC
  - MCD
  - MCL
  - MCPE
  - REALMS
  - WEB

fieldShortcuts:
  category: cf[11901]
  confirmation: Confirmation Status
  gamemode: Game Mode
  mp: Mojang Priority
  version: affectedVersion

containsSearchSyntax:
  - ado
  - comment
  - description
  - environment
  - summary
  - text

prebuiltClauses:
  commenter: issueFunction in commented("by $?")
  transitionedby: status changed by $!

request:
  invalidTicketEmoji: â¸
  noLinkEmoji: â›”
  warningLifetime: 5000
  waitingEmoji: âŒ›

  invalidRequestJql: created > -24h

  suggestedEmoji:
    - âœ…
    - â˜‘ï¸
    - âŒ
    - ğŸ’¬

  ignorePrependResponseMessageEmoji: âœ…
  ignoreResolutionEmoji: ğŸ’¬

  resolveDelay: 10000
  progressMessageAddDelay: 10000
  prependResponseMessage: whenResolved
  prependResponseMessageInLog: false

  responseMessage: |-
    ```
    {{author}} {{url}}
    {{message}}

    ```
