# 1. Copy this file
# 2. Rename the copy to `local.yml`
# 3. Change the bot token and save the file
#
# You can add more configs if you want to.
#
# You can also use `local-beta.yml` for the beta bot configuration, or `local-main.yml` for the main configuration.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Never commit any of the local files.
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

token: <your bot token>